name: Swift Build and Test
on:
  push:
  pull_request:

jobs:
  macos-build:
    name: Build and Test on macOS
    runs-on: macos-15
    steps:
      - name: Select Xcode 16.3
        run: |
          XCODE_PATH=$(ls -d /Applications/Xcode_16.3*.app | head -n 1)
          echo "Using Xcode at $XCODE_PATH"
          sudo xcode-select -s "$XCODE_PATH/Contents/Developer"
          xcodebuild -version
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: swift build --package-path Core
      - name: Test
        run: swift test --package-path Core

  xcodebuild-test:
    name: Xcodebuild test on macOS
    runs-on: macos-15
    steps:
      - name: Select Xcode 16.3
        run: |
          XCODE_PATH=$(ls -d /Applications/Xcode_16.3*.app | head -n 1)
          echo "Using Xcode at $XCODE_PATH"
          sudo xcode-select -s "$XCODE_PATH/Contents/Developer"
          xcodebuild -version
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Verify xcodebuild installation
        run: xcodebuild -version
      - name: List available schemes
        run: xcodebuild -project azooKeyMac.xcodeproj -list
      - name: Test building azooKeyMac (Release configuration)
        run: |
         xcodebuild \
          -project azooKeyMac.xcodeproj \
          -scheme azooKeyMac \
          -configuration Release \
          -destination 'generic/platform=macOS' \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY=""

  swiftlint:
    name: SwiftLint
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install SwiftLint
        run: |
          brew update
          brew install swiftlint
      - name: Check SwiftLint version
        run: swiftlint version
      - name: Run SwiftLint
        run: |
          swiftlint --fix --format
          swiftlint --quiet --strict
  